build:
  version: "3.0 version"

accounts:
  message: "Welcome to eazy back account related local APIs"
  contactDetails:
    name: "Badri Prasad Verma"
    email: badriverma135@gmail.com
  onCallSupport:
    -(555)555-1234
    -(555)555-1234