build:
  version: "2.0 version"

accounts:
  message: "Welcome to eazy back account related qa APIs"
  contactDetails:
    name: "Badri Prasad Verma QA"
    email: badriverma135@gmail.com
  onCallSupport:
    -(555)555-1234
    -(555)555-1234