build:
  version: "3.0"

cards:
  message: "Welcome to eazy bank cards related local apis"
  contactDetails:
    name: "Badri Verma Backend Developer"
    email: "badribackend@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932