server:
  port: 8090
spring:
  application:
    name: "loans"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:udemyMicroservices
    username: root
    password: Badri@2001
  h2:
    console:
      enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    compatibility-verifier:
      enabled: false
  config:
    import: "optional:configserver:http://localhost:8071/"
