server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:udemyMicroservices
    username: root
    password: Badri@2001
  h2:
    console:
      enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import:
      - "application-qa.yml"
      - "application-prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs "
  contactDetails:
    name: "Badri Verma - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8