server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:udemyMicroservices
    username: root
    password: Badri@2001
  h2:
    console:
      enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application-prod.yml"
      - "application-qa.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

cards:
  message: "Welcome to eazy bank cards related local apis"
  contactDetails:
    name: "Badri Verma Backend Developer"
    email: "badribackend@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932