server:
  port: 9000
spring:
  datasource:
    url: jdbc:h2:mem:udemyMicroservices
    username: root
    password: Badri@2001
  h2:
    console:
      enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true