server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    compatibility-verifier:
      enabled: false
  config:
    server:
      native:
#        search-locations: "classpath:/config"
        search-locations: "filepath:///C://config"